# Generated by Django 3.2.4 on 2021-12-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("messenger_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_read_message_user1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="messenger_backend.message",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_read_message_user2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="messenger_backend.message",
            ),
        ),
    ]
