# Generated by Django 3.2.4 on 2021-12-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_auto_20211207_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_read_message_user1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_read_message_user2',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
